export const GET_BACKGROUND_PHOTO_SUCCESS = 'GET_BACKGROUND_PHOTO_SUCCESS';
export const GET_BACKGROUND_PHOTO_START = 'GET_BACKGROUND_PHOTO_START';
export const GET_BACKGROUND_PHOTO_ERROR = 'GET_BACKGROUND_PHOTO_ERROR';
export const GET_BACKGROUND_PHOTO = 'GET_BACKGROUND_PHOTO';

export const GET_TOPICS_LIST = 'GET_TOPICS_LIST';
